# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refresh_token.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, "", "refresh_token.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13refresh_token.proto\x12\x12refresh_auth_token"7\n\x12RefreshAuthRequest\x12\x0e\n\x06\x63ookie\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t";\n\x13RefreshAuthResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x12\n\nauth_token\x18\x02 \x01(\t2r\n\x0b\x41uthService\x12\x63\n\x10RefreshAuthToken\x12&.refresh_auth_token.RefreshAuthRequest\x1a\'.refresh_auth_token.RefreshAuthResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "refresh_token_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REFRESHAUTHREQUEST"]._serialized_start = 43
    _globals["_REFRESHAUTHREQUEST"]._serialized_end = 98
    _globals["_REFRESHAUTHRESPONSE"]._serialized_start = 100
    _globals["_REFRESHAUTHRESPONSE"]._serialized_end = 159
    _globals["_AUTHSERVICE"]._serialized_start = 161
    _globals["_AUTHSERVICE"]._serialized_end = 275
# @@protoc_insertion_point(module_scope)
