name: Linter

on: [pull_request]

jobs:
    lint-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Lint
              uses: chartboost/ruff-action@v1
            - name: Check Format
              uses: chartboost/ruff-action@v1
              with:
                  args: 'format --check'
